# Generated by Django 5.2 on 2025-05-05 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('updation_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='CertificateType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('certificate_type', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tcertificatetype',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(blank=True, max_length=150, null=True)),
                ('department_short_name', models.CharField(max_length=100)),
                ('department_code', models.CharField(blank=True, max_length=50, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbldepartments',
            },
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('institute_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'institute',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sid', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('father_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email_id', models.EmailField(max_length=200, unique=True)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=255)),
                ('pursuing_class', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=11)),
                ('status', models.BooleanField(null=True)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('nss', models.BooleanField(null=True)),
                ('age', models.PositiveIntegerField(null=True)),
                ('contact_no', models.CharField(max_length=15)),
                ('institute_id', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.user')),
            ],
            options={
                'db_table': 'tstudent',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('certificate_type', models.CharField(max_length=110)),
                ('description', models.TextField()),
                ('posting_date', models.DateTimeField(auto_now_add=True)),
                ('admin_remark', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Waiting'), (1, 'Approved'), (2, 'NotApproved')], default=1)),
                ('is_read', models.IntegerField(choices=[(0, 'Unread'), (1, 'Read')], default=0)),
                ('admin_action_taken_date', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='users.userprofile')),
            ],
            options={
                'db_table': 'tcertificate',
            },
        ),
    ]
