# Generated by Django 5.2 on 2025-05-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='institute_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
