# Generated by Django 5.2 on 2025-05-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_institute_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='contact_no',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
