# Generated by Django 5.2 on 2025-05-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_admin_institute_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='institute_id',
            field=models.PositiveIntegerField(),
        ),
    ]
