# Generated by Django 5.2 on 2025-05-06 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_admin_institute_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='institute_id',
        ),
    ]
