# Generated by Django 5.2 on 2025-05-06 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_admin_institute_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='institute_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='institute', to='users.institute'),
            preserve_default=False,
        ),
    ]
