# Generated by Django 5.1.4 on 2025-01-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
