# Generated by Django 5.1.4 on 2025-01-18 12:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('updation_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='CertificateType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('certificate_type', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tcertificatetype',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(blank=True, max_length=150, null=True)),
                ('department_short_name', models.CharField(max_length=100)),
                ('department_code', models.CharField(blank=True, max_length=50, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbldepartments',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='Unknown', max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(default='General', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dob',
            field=models.CharField(default='2000-01-01', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_id',
            field=models.EmailField(default='example@example.com', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='John', max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default='Male', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.CharField(blank=True, default='default.jpg', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, default='Doe', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=11),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pursuing_class',
            field=models.CharField(default='N/A', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sid',
            field=models.CharField(default='SID000', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact_no',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='tstudent',
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('certificate_type', models.CharField(max_length=110)),
                ('pursuing_class', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('posting_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin_remark', models.TextField(blank=True, null=True)),
                ('admin_remark_date', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')])),
                ('is_read', models.IntegerField(choices=[(0, 'Unread'), (1, 'Read')])),
                ('sid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userprofile')),
            ],
            options={
                'db_table': 'tcertificate',
            },
        ),
    ]
