# Generated by Django 5.1.4 on 2025-01-25 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_certificate_posting_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='admin_remark_date',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='pursuing_class',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='sid',
        ),
        migrations.AddField(
            model_name='certificate',
            name='user_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='users.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificate',
            name='is_read',
            field=models.IntegerField(choices=[(0, 'Unread'), (1, 'Read')], default=0),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
        ),
    ]
